events {}

http {
  include /etc/nginx/mime.types;

  gzip on;
  gzip_types text/css application/javascript application/json;
  gzip_min_length 1024;

  server {
    listen 80;
    charset utf-8;
    server_tokens off;
    absolute_redirect off;

    # Proxy /api requests to the API service (HTTP)
    location /api/ {
        fastcgi_pass   api:9000;
        fastcgi_param  SCRIPT_FILENAME  /var/www/html/api/public/index.php;
        include        fastcgi_params;
        fastcgi_param  REQUEST_METHOD   $request_method;
        fastcgi_param  REQUEST_URI      $request_uri;
        fastcgi_param  QUERY_STRING     $query_string;
        fastcgi_hide_header X-Powered-By;
    }

    # All other requests go to the frontend
    location = / {
      return 301 /sis-rme/;
    }
    location = /sis-rme {
      return 301 /sis-rme/;
    }

    # nosemgrep: generic.nginx.security.alias-path-traversal.alias-path-traversal
    location = /sis-rme/config.json {
      alias /var/www/html/frontend/;
      try_files config.json =404;
    }

    location ~* ^/sis-rme/assets/fonts/(.+\.woff2)$ {
      alias /var/www/html/frontend/assets/fonts/$1;
      expires 90d;
      add_header Cache-Control "public, max-age=7776000";
    }

    location ~* ^/sis-rme/assets/(.+\.(js|css))$ {
      alias /var/www/html/frontend/assets/$1;
      expires 1y;
      add_header Cache-Control "public, max-age=31536000, immutable";
    }

    location /sis-rme/ {
      alias /var/www/html/frontend/;
      try_files $uri $uri/ /sis-rme/index.html;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
      root   /usr/share/nginx/html;
    }
  }
}

