include /etc/nginx/conf.d/options/json_analytics.conf;
include /etc/nginx/conf.d/servers/*.conf;

upstream sis-rme_backend {
  server 127.0.0.1:81;
}

upstream sis-dde_backend {
  server 127.0.0.1:3000;
}


